version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  precommit:
    executor: python/default
    steps:
      - checkout
      - run:
          command: pip install pre-commit
          name: Install pre-commit
      - run:
          command: pre-commit run --all-files
          name: Format Check

  test:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          command: python -bb -m pytest tests/
          name: Test

workflows:
  main:
    jobs:
      - precommit
      - test
